version: '3.7'

services:
  app:
    build: ./app
    container_name: node-app
    expose:
      - "3000"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - app
